# Generated by Django 5.2.6 on 2025-11-09 01:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentalerts",
            name="attendance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="records.attendance",
            ),
        ),
        migrations.AlterField(
            model_name="parentalerts",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="parentalerts",
            name="mark",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="records.mark",
            ),
        ),
        migrations.AlterField(
            model_name="parentalerts",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="parentalerts",
            name="modified_by",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="parentalerts",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Sent", "Sent"),
                    ("Read", "Read"),
                    ("Failed", "Failed"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="parentalerts",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
